# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "dm-snapshot" "amdgpu" "kvm-amd" "k10temp" "nct6775" "ddcci" "ddcci_backlight" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ ddcci-driver ];

  boot.initrd.luks.devices.main =
    { device = "/dev/disk/by-partuuid/0d2db233-2104-49a6-a9ef-0f5748fe9989";
      preLVM = true;
    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7944672b-dbfd-48e9-a470-20d7d4ea6ccc";
      fsType = "ext4";
      options = ["noatime" "nodiratime"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4EFB-A6E8";
      fsType = "vfat";
    };

  swapDevices = [{ device = "/dev/disk/by-uuid/c41af588-2f60-46d9-8b53-8ab5b05ab767"; }];

  hardware.enableAllFirmware = true;
  hardware.firmware = with pkgs; [ firmwareLinuxNonfree wireless-regdb ];
  hardware.enableRedistributableFirmware = true;
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
    extraPackages = with pkgs; [ 
      amdvlk 
      rocm-opencl-icd 
      rocm-opencl-runtime
      mesa
    ];
  };

  hardware.logitech.wireless.enable = true;
  hardware.logitech.wireless.enableGraphical = true;

  hardware.bluetooth = {
    enable = true;
    package = pkgs.bluezFull;
    powerOnBoot = true;
    settings.General.Enable = "Source,Sink,Media,Socket";
  };
}
