# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [ "dm-snapshot" "amdgpu" "kvm-amd" "k10temp" "nct6775" "i2c-dev" "uvcvideo" "btusb" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ ddcci-driver ];
  boot.extraModprobeConfig = ''
    options ddcci dyndbg delay=400
    options ddcci_backlight dyndbg
  '';

  boot.initrd.luks.devices = {
    main = {
      device = "/dev/disk/by-partuuid/0d2db233-2104-49a6-a9ef-0f5748fe9989";
      preLVM = true;
    };

    media = {
      device = "/dev/disk/by-uuid/02cd560e-e103-4ac7-b31e-c9da8e05685e";
      allowDiscards = true;
      preLVM = true;
    };

    backup = {
      device = "/dev/disk/by-uuid/9c2adebf-9f6d-48bd-a06b-ff03887a6d4c";
      allowDiscards = true;
      preLVM = true;
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7944672b-dbfd-48e9-a470-20d7d4ea6ccc";
    fsType = "ext4";
    options = ["noatime" "nodiratime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4EFB-A6E8";
    fsType = "vfat";
  };

  fileSystems."/home/rb/Media" = {
    device = "/dev/disk/by-label/media";
    fsType = "ext4";
    options = ["rw" "data=ordered" "noatime" "nodiratime"];
  };

  fileSystems."/home/rb/Backup" = {
    device = "/dev/disk/by-label/backup";
    fsType = "ext4";
    options = ["rw" "data=ordered" "noatime" "nodiratime"];
  };

  swapDevices = [{ device = "/dev/disk/by-uuid/c41af588-2f60-46d9-8b53-8ab5b05ab767"; }];

  hardware.enableAllFirmware = true;
  hardware.firmware = [ pkgs.firmwareLinuxNonfree pkgs.wireless-regdb ];
  hardware.enableRedistributableFirmware = true;
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
    extraPackages = with pkgs; [ amdvlk libvdpau-va-gl mesa libva ];
  };

  hardware.bluetooth = {
    enable = true;
    package = pkgs.bluezFull;
    powerOnBoot = true;
  };

  hardware.i2c.enable = true;
}
