# Do not modify this file!  It was generated by ‘nixos-generate-config’ and may
# be overwritten by future invocations.  Please make changes to
# /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.kernelPackages = pkgs.linuxPackages_6_0;

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [ "dm-snapshot" "amdgpu" "kvm-amd" "k10temp" "nct6775" "i2c-dev" "uvcvideo" "btusb" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ ddcci-driver ];
  boot.extraModprobeConfig = ''
    options ddcci dyndbg delay=400
    options ddcci_backlight dyndbg
  '';

  boot.kernel.sysctl = {
    "net.core.rmem_max" = 4194304;
    "net.core.wmem_max" = 1048576;
  };

  boot.initrd.luks.devices = {
    main = {
      device = "/dev/disk/by-partuuid/0d2db233-2104-49a6-a9ef-0f5748fe9989";
      preLVM = true;
    };

    media = {
      device = "/dev/disk/by-uuid/02cd560e-e103-4ac7-b31e-c9da8e05685e";
      allowDiscards = true;
      preLVM = true;
    };

    backup = {
      device = "/dev/disk/by-uuid/9c2adebf-9f6d-48bd-a06b-ff03887a6d4c";
      allowDiscards = true;
      preLVM = true;
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7944672b-dbfd-48e9-a470-20d7d4ea6ccc";
    fsType = "ext4";
    options = ["noatime" "nodiratime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4EFB-A6E8";
    fsType = "vfat";
  };

  fileSystems."/home/rb/Media" = {
    device = "/dev/disk/by-label/media";
    fsType = "ext4";
    options = ["rw" "data=ordered" "noatime" "nodiratime"];
  };

  fileSystems."/home/rb/Backup" = {
    device = "/dev/disk/by-label/backup";
    fsType = "ext4";
    options = ["rw" "data=ordered" "noatime" "nodiratime"];
  };

  swapDevices = [{ device = "/dev/disk/by-uuid/c41af588-2f60-46d9-8b53-8ab5b05ab767"; }];

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "20.09"; # Did you read the comment?
}
